version: '3.8'
name: beatbuddy-playlist

services:
  playlist-db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=beatbuddy_playlist
      - POSTGRES_USER=bbplaylistdb
      - POSTGRES_PASSWORD=bbplaylistdb
      - PGPASSWORD=bbplaylistdb
    ports:
      - 5431:5432
    networks:
      - default
#    volumes:
#      - ./initdb.d/:/docker-entrypoint-initdb.d/

  playlist-ms:
    image: docker.io/maven:3.9.6-eclipse-temurin-17
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://playlist-db:5432/beatbuddy_playlist
      - SPRING_DATASOURCE_USERNAME=bbplaylistdb
      - SPRING_DATASOURCE_PASSWORD=bbplaylistdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.50.36:8000/eureka
      - SERVER_PORT=8110
      - USER=vutiendat3601
    ports:
      - 8110:8110
      - 60000:60000
    volumes:
      - ./:/opt/beatbuddy/playlist/
      - ~/.m2:/root/.m2
    command: mvn -f /opt/beatbuddy/playlist/pom.xml spring-boot:run
    networks:
      - default

networks:
  default:
    name: beatbuddy
    external: true
