version: '3.8'
name: beatbuddy-playlist

services:
  playlist-db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=beatbuddy_playlist
      - POSTGRES_USER=bbplaylistdb
      - POSTGRES_PASSWORD=bbplaylistdb
      - PGPASSWORD=bbplaylistdb
    ports:
      - 5431:5432
    networks:
      - default
#    volumes:
#      - ./initdb.d/:/docker-entrypoint-initdb.d/

networks:
  default:
    name: beatbuddy-playlist
    driver: bridge
