name: Java CI/CD with Maven, Docker

on:
  pull_request:
    branches: [ "stag" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.1-bookworm
        env:
          POSTGRES_DB: beatbuddy_playlist
          POSTGRES_USER: bbplaylistdb
          POSTGRES_PASSWORD: bbplaylistdb
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U bbplaylistdb" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  push:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_READ_WRITE_TOKEN }}
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build docker image and push to Docker Hub
      run: mvn clean install -DskipTests jib:build
